version: '3.8'
services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  backend:
    restart: always
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    restart: always
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'

  e2e-tests:
    depends_on:
      - frontend
    build:
      context: ./e2e-tests
      dockerfile: Dockerfile

  selenium:
    image: selenium/standalone-chrome
    restart: always
    shm_size: 2gb

volumes:
  db:
    driver: local