version: '3.8'
services:


  e2e-tests:
    depends_on:
      - selenium
    build:
      context: ./e2e-tests
      dockerfile: Dockerfile

  selenium:
    image: selenium/standalone-chrome
    restart: always
    shm_size: 2gb

volumes:
  db:
    driver: local